spring:
  application:
    name: demo-edge-service
zuul:
  routes:
    app:
      path: /time/**
      url: http://worldclockapi.com/api/json/est
azure:
  application-insights:
    instrumentation-key: eeb3e6b7-a23d-43a5-9558-2ab615cfc1c6